sudo: true
dist: trusty

language: clojure

before_install:
  - ./.travis/install-dependencies.sh 

script:
  - ./functional_tests/bionitio-test.sh -p $TRAVIS_BUILD_DIR/bin/bionitio-clj -d functional_tests/test_data
  - ./.travis/unit-test.sh
