sudo: true
dist: xenial 
services:
  - docker

before_install:
#  - ./.travis/install-dependencies.sh 
  - docker build -t bionitio-clojure .

script:
#  - ./functional_tests/bionitio-test.sh -p $TRAVIS_BUILD_DIR/bin/bionitio -d functional_tests/test_data
#  - ./.travis/unit-test.sh
  - docker run --entrypoint /bionitio/.travis/unit-test.sh bionitio-clojure
  - docker run --entrypoint /bionitio/functional_tests/bionitio-test.sh bionitio-clojure -p bionitio -d /bionitio/functional_tests/test_data -v
~            
